# Generated by Django 5.0.3 on 2024-03-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipousuario',
            field=models.CharField(max_length=10),
        ),
    ]
