# Generated by Django 5.0.3 on 2024-03-21 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usuario_tipousuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidoMat',
            new_name='apellidomat',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidoPat',
            new_name='apellidopat',
        ),
    ]
