# Generated by Django 5.0.3 on 2024-03-31 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_impuestosegcategoria_tipoperiodo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gente',
        ),
    ]
